# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2ff154daf16855cb604126fcde84756920d0922fedea36ff94695e10e4f433c4bbe6e9073ed3b50efb1d94ded66f0928ccb5e14d55401ed0a178561c3e4d30

test:
  secret_key_base: b6b4a2dc97ad99bfafa5b4b20dcb26da5fd8af3f5ecaf30cd5ded41554e984fffb684c3e584251447ecfbc3442a48279df4af83e19dcfa56b7304f6631658d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
